accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
                                

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('signup', views.signup_view, name="signup"),
    path('verfy', views.verify, name="verify"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_screen, name="home"),
    path('profile/<user_id>/', views.profile_view, name="profile"),
    
]

stealth_intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('carsify-auth/', include('accounts.urls')),
    #path('', include('django.contrib.auth.urls')),
    path('accounts/login/',views.login_view, name="login"),
    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

class AccountManager(BaseUserManager):
    def create_user(self, email, username, password=None):
        if not email:
            raise ValueError('Email address is required.')
        if not username:
            raise ValueError('Username is required.')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        user = self.create_user(
            email=self.normalize_email(email),
            password=password,
            username=username,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class Accounts(AbstractBaseUser):
    email 					= models.EmailField(verbose_name="email", max_length=60, unique=True)
    username 				= models.CharField(max_length=30, unique=True)
    first_name              = models.CharField(max_length=30,default='')
    last_name               = models.CharField(max_length=30,default='')
    date_joined				= models.DateTimeField(verbose_name='date joined', auto_now_add=True)
    last_login				= models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin				= models.BooleanField(default=False)
    is_active				= models.BooleanField(default=True)
    is_staff				= models.BooleanField(default=False)
    is_superuser			= models.BooleanField(default=False)
    

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = AccountManager()

    def __str__(self):
        return self.username

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES)
    def has_module_perms(self, app_label):
        return True

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

from .models import Accounts


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=254, help_text='Required. Add a valid email address.')

    class Meta:
        model = Accounts
        fields = ('email', 'username', 'first_name', 'last_name', 'password1', 'password2' )

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        try:
            account = Accounts.objects.get(email=email)
        except Accounts.DoesNotExist:
            return email
        raise forms.ValidationError(f'Email {email} already exists.')

    def clean_username(self):
        username = self.cleaned_data['username']
        try:
            account = Accounts.objects.get(username=username)
        except Accounts.DoesNotExist:
            return username
        raise forms.ValidationError(f'Username {username} already exists.')


class AccountLoginForm(forms.ModelForm):

	password = forms.CharField(label='Password', widget=forms.PasswordInput)

	class Meta:
		model = Accounts
		fields = ('email', 'password')

	def clean(self):
		if self.is_valid():
			email = self.cleaned_data['email']
			password = self.cleaned_data['password']
			if not authenticate(email=email, password=password):
				raise forms.ValidationError("Invalid login")

accounts/views.py
from accounts.models import Accounts
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, authenticate, logout
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail, EmailMessage
from django.contrib.sites.shortcuts import get_current_site
from django.template.loader import render_to_string
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.utils.encoding import force_bytes, force_text

from .tokens import generate_token

from .forms import RegistrationForm, AccountLoginForm



def signup_view(request, *args, **kwargs):
    user = request.user
    if user.is_authenticated: 
        return HttpResponse("You are already authenticated as " + str(user.email))

    context = {}
    if request.POST:
        form = RegistrationForm(request.POST)
        if form.is_valid():
            
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email').lower()
            raw_password = form.cleaned_data.get('password1')
            first_name = form.cleaned_data.get('first_name')
            last_name = form.cleaned_data.get('last_name')
            form.save()
            #account = authenticate(email=email, password=raw_password)
            #login(request, account)
            #destination = get_redirect_if_exists(request)
            #if destination:
            #	return redirect(destination)
            #return redirect('home')
            new_user = Accounts.objects.get(email=email, username=username)
            new_user.first_name = first_name
            new_user.last_name = last_name
            new_user.is_active = False

            new_user.save()

            current_site = get_current_site(request)
            email_subject = "Carsify- Confirmation Mail!"
            message = render_to_string('accounts/email_confirmation.html',{
                    'name': new_user.username,
                    'domain': current_site.domain,
                    'uid': urlsafe_base64_encode(force_bytes(new_user.pk)),
                    'token': generate_token.make_token(new_user)
            })
            email = EmailMessage(
                email_subject, 
                message,
                settings.EMAIL_HOST_USER,
                [new_user.email],
            )
            email.fail_silently = True
            email.send()

            return render(request, 'accounts/signup_verify.html', {'name': new_user.username})


        else:
            context['registration_form'] = form

    else:
        form = RegistrationForm()
        context['registration_form'] = form
    return render(request, 'accounts/signup.html', context)




def login_view(request, *args, **kwargs):
    context = {}

    user = request.user
    if user.is_authenticated: 
        return redirect("home:home")

    if request.POST:
        form = AccountLoginForm(request.POST)
        if form.is_valid():
            email = request.POST['email']
            password = request.POST['password']
            user = authenticate(email=email, password=password)

            if user:
                login(request, user)
                destination = get_redirect_if_exists(request)
                if destination:
                    return redirect(destination)
                return redirect("home:home")
        else:
             context['login_form'] = form
        
    else:
        form = AccountLoginForm()
        context['login_form'] = form

    return render(request, "accounts/login.html", context)




@login_required
def logout_view(request):
	logout(request)
	return redirect("home:home")



def get_redirect_if_exists(request):
	redirect = None
	if request.GET:
		if request.GET.get("next"):
			redirect = str(request.GET.get("next"))
	return redirect




def verify(request):
     return render(request, 'accounts/signup_verify.html')




def activate(request, uidb64, token):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        new_user = Accounts.objects.get(pk=uid)

    except (TypeError, ValueError, OverflowError, Accounts.DoesNotExist):
        new_user = None

    if new_user is not None and generate_token.check_token(new_user, token):
        new_user.is_active = True
        new_user.save() 
        return redirect('accounts:login')
    else:
        return HttpResponse("Activation Failed!")

templates/accounts/email_confirmation.html
{% autoescape off %}

Welcome to Stealth - Carsify

Hello {{ name }}!

Thank you for registering in our website. In order to activate your account, please confirm your email by clicking the following link.

Confirmation Link: http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}

Thank you
Vimal
(Carsify)

{% endautoescape %}

templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}


{% block content %}


<style type="text/css">

  .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px; 
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }


</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin" style='margin-top: 100px;'>
		  <div class="card-body">
		    <form class="form-signin" method="post">
            {% csrf_token %}
				<div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" style='backgound:none;' src="{% static "images/car.png" %}" alt="Carsify logo" width="150" height="80">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required>
                <br>
				{% for field in login_form %}
				<p>
                    {% for error in field.errors %}
                    <p style="color: red;">{{ error }}</p>
                    {% endfor %}
				</p>
				{% endfor %}
				{% if login_form.non_field_errors %}
                    <div style="color: red">
                    <p style="color: red;">{{login_form.non_field_errors}}</p>
                    </div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" style='margin-left: 60px; width: 200px;' type="submit">Log in</button>
				</form>

				<div class="d-flex flex-column my-4">
					<p style='color:black; margin-left:42px'>Forgot Password? <a class="m-auto" href="{% url 'reset_password' %}">Reset Password</a></p>
				</div>
		  </div>
		</div>
		
	</div>
</div>






{% endblock content %}

templates/accounts/password_reset.html
{% extends "base.html" %}

{% block content %}

<div style='margin: 50px 50px;'>

<h3>Password reset</h3>
<br>
<p>Forgotten your password? Enter your email address below, and we’ll email instructions for setting a new one.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Send email">
	
</form>

</div>

{% endblock content %}

templates/accounts/password_reset_done.html
{% extends "base.html" %}

{% block content %}

<div style='margin: 50px 50px;'>
<h3>Password reset complete</h3>
<br>
<p>Your password has been set. You may go ahead and log in now.</p>

<a href="{% url 'accounts:login' %}">Log in</a>

</div>

{% endblock content %}

templates/accounts/password_reset_form.html
{% extends "base.html" %}

{% block content %}

<div style='margin: 50px 50px;'>

<h3>Enter new password</h3>
<br>

<p>Please enter your new password twice so we can verify you typed it in correctly.</p>

<form method="post">

	{% csrf_token %}
	{{form}}
	<input type="Submit" name="Update Password">
	
</form>

</div>

{% endblock content %}

templates/accounts/password_reset_sent.html
{% extends "base.html" %}

{% block content %}

<div style='margin: 50px 50px;'>

<h3>Password reset sent</h3>
<br>

<p>We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.</p>

<p>If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.</p>

</div>

{% endblock content %}

templates/accounts/signup.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<style type="text/css">

  .card-signin {
	  width: 100%;
	  max-width: 400px;
	  padding: 15px;
	  margin: auto;
  }
  
  .form-signin input[type="email"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="text"] {
    margin-bottom: 10px;
    border-bottom-right-radius: 0;
    border-bottom-left-radius: 0;
  }
  .form-signin input[type="password"] {
    margin-bottom: -1px;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
  }


</style>

<div class="container-fluid">
	<div class="row justify-content-center">
		<div class="card card-signin" style='margin-top: 70px;'>
		  <div class="card-body">
		    <form class="form-signin" method="post">
             {% csrf_token %}
				<div class="d-flex flex-column pb-3">
				<img class="img-fluid mx-auto d-block" style='backgound:none;' src="{% static "images/car.png" %}" alt="Carsify logo" width="150" height="80">
				</div>
				<input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus>

				<input type="text" name="username" id="inputUsername" class="form-control" placeholder="Username" required>

				<input type="text" name="first_name" id="inputfirst_name" class="form-control" placeholder="First name" required>

				<input type="text" name="last_name" id="inputlast_name" class="form-control" placeholder="Last name" required>

				<input type="password" name="password1" id="inputPassword1" class="form-control" placeholder="Password" required>
				<br>
				<input type="password" name="password2" id="inputPassword2" class="form-control" placeholder="Confirm password" required>
				<br>
				{% for field in registration_form %}
				<p>
				{% for error in field.errors %}
				<p style="color: red">{{ error }}</p>
				{% endfor %}
				</p>
				{% endfor %}
				{% if registration_form.non_field_errors %}
				<div style="color: red">
					<p>{{registration_form.non_field_errors}}</p>
				</div>

				{% endif %}

				<button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>

				</form>
		  </div>
		</div>
		
	</div>
</div>






{% endblock content %}

templates/accounts/signup_verify.html
{% extends 'base.html' %}
{% block content %}

<div style='margin: 50px 50px;'>
      <div>
        <h3>Hello {{ name }}!</h3>
        <br>
        <p>Your Account has been created successfully! <br>We have sent a confirmation mail to your registered email, please verify your email and login in order to activate your account.</p>
      </div>
        <button type="button" value="Gmail">Gmail
            <a href='https://mail.google.com/'></a>
        </button>
</div>
        
{% endblock content %}