accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
                                

app_name = 'accounts'
urlpatterns = [
    path('login', views.login_view, name="login"),
    path('logout', views.logout_view, name="logout"),
    path('signup', views.signup_view, name="signup"),
    path('verfy', views.verify, name="verify"),
    path('activate/<uidb64>/<token>', views.activate, name="activate"),
    
]

home/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.home_screen, name="home"),
    path('profile/<user_id>/', views.profile_view, name="profile"),
    
]

stealth_intern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from accounts import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('carsify-auth/', include('accounts.urls')),
    #path('', include('django.contrib.auth.urls')),
    path('accounts/login/',views.login_view, name="login"),
    path('reset_password/',
    auth_views.PasswordResetView.as_view(template_name="accounts/password_reset.html"),
    name="reset_password"),

    path('reset_password_sent/', 
        auth_views.PasswordResetDoneView.as_view(template_name="accounts/password_reset_sent.html"), 
        name="password_reset_done"),

    path('reset/<uidb64>/<token>/',
     auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_form.html"), 
     name="password_reset_confirm"),

    path('reset_password_complete/', 
        auth_views.PasswordResetCompleteView.as_view(template_name="accounts/password_reset_done.html"), 
        name="password_reset_complete"),
]

templates/snippets/base_css.html
<style type="text/css">
	head{
		font-family: "Segoe UI";
		font-weight: 380;
	}
	footer{
		font-family: "Segoe UI";
		font-weight: 380;
	}
	body{
		background-color: #f2f2f2;
		font-family: "Segoe UI";
		font-weight: 380;
	}

	:root{
		--main-background-color: #f2f2f2;
		--dark-background-color: #a2a2a2;
		--secondary-text-color: #808080;
		--light-primary-text-color: #0080ff;
	}
	
	


</style>

templates/snippets/footer.html
<style type="text/css">
	.footer{
		min-height: 100px;
	}
</style>

<!-- Footer -->

<div class="d-flex flex-row align-items-center footer bg-dark shadow-lg mt-4">
	<p class="m-auto" style='color:#fff;'>@Stealth - Carsify  |  2021</p>
</div>

templates/snippets/header.html
<style>

.container-fluid{
    
    padding : 5px 30px;
    color: white;
}



</style>


<nav class="navbar navbar-light bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" style="color:white;">Stealth - Carsify</a>
    <form class="d-flex">
        <span style='margin-right:30px; padding-top:5px'><a class="p-2 text-light" style='text-decoration:none;' href="{% url 'home:home' %}">Home</a></span>
        {% if request.user.is_authenticated %}
            <span style='margin-right:30px; padding-top:5px'><a class="p-2 text-light" style='text-decoration:none;' href="{% url 'home:profile' user_id=request.user.id %}">My Profile</a></span>
            <span style='margin-right:30px; padding-top:5px'><a class="p-2 text-light" style='text-decoration:none;' href="{% url 'accounts:logout' %}">Logout</a></span>
        {% else %}
            <span style='margin-right:30px; padding-top:5px'><a class="p-2 text-light" style='text-decoration:none;' href="{% url 'accounts:login' %}">Login</a></span>
            <a class="btn btn-outline-primary" href="{% url 'accounts:signup' %}">Sign-up</a>
		{% endif %}	
    </form>
  </div>
</nav>